const express = require('express')
const path = require('path');
const app = express();
const bodyParser = require('body-parser');
const axios = require('axios');

app.use( bodyParser.json() );       // to support JSON-encoded bodies
app.use(bodyParser.urlencoded({     // to support URL-encoded bodies
  extended: true
}));

app.set('view engine', 'pug');

const getGifs = async (query="cats") => {
  try {
    const url = "https://api.giphy.com/v1/gifs/search";
    const response = await axios({
      url,
      method: 'get',
      params: {
        api_key: 'a0PNjGEVofdNdLAo5Xeh0mcNcKea716v',
        q: query,
        limit: 25,
        offset: 0,
        rating: 'G',
        lang: 'en'
      }
    })
    return response.data;
  } catch (error) {
    console.log("error: \n");
    console.error(error);
  }
}


// async middleware to be used on async route cb fns
// great because we dont need a try/catch block in every route
const asyncMiddleware = fn =>
  (req, res, next) => {
    Promise.resolve(fn(req, res, next))
      .catch(next);
  };




app.get('/', (req, res) => res.render(path.join(__dirname, 'index')));
app.post('/search', asyncMiddleware( async (req, res, next) => {
  // console.log(req.body);
  // const data = await getGifs();
  // console.log("here's the data \n");
  // console.log(data);

  const data = [ { type: 'gif',
       id: 'Ov5NiLVXT8JEc',
       slug: 'cats-light-sabers-Ov5NiLVXT8JEc',
       url: 'https://giphy.com/gifs/cats-light-sabers-Ov5NiLVXT8JEc',
       bitly_gif_url: 'https://gph.is/1B5sZnz',
       bitly_url: 'https://gph.is/1B5sZnz',
       embed_url: 'https://giphy.com/embed/Ov5NiLVXT8JEc',
       username: '',
       source: 'https://hobolunchbox.tumblr.com/post/96197585095/the-force-is-strong-with-mr-pickles',
       rating: 'g',
       content_url: '',
       source_tld: 'hobolunchbox.tumblr.com',
       source_post_url: 'https://hobolunchbox.tumblr.com/post/96197585095/the-force-is-strong-with-mr-pickles',
       is_sticker: 0,
       import_datetime: '2014-08-30 20:50:33',
       trending_datetime: '2015-10-19 21:26:46',
       images: [Object],
       title: 'star wars fighting GIF',
       _score: 2500076.8 },
     { type: 'gif',
       id: 'cfuL5gqFDreXxkWQ4o',
       slug: 'cat-cool-cats-cfuL5gqFDreXxkWQ4o',
       url: 'https://giphy.com/gifs/cat-cool-cats-cfuL5gqFDreXxkWQ4o',
       bitly_gif_url: 'https://gph.is/2I5xics',
       bitly_url: 'https://gph.is/2I5xics',
       embed_url: 'https://giphy.com/embed/cfuL5gqFDreXxkWQ4o',
       username: 'Bubblepunk',
       source: '',
       rating: 'g',
       content_url: '',
       source_tld: '',
       source_post_url: '',
       is_sticker: 0,
       import_datetime: '2018-03-04 20:50:43',
       trending_datetime: '2018-03-31 09:00:01',
       user: [Object],
       images: [Object],
       title: 'on my way goodbye GIF by Bubble Punk',
       _score: 2300066.5 },
     { type: 'gif',
       id: 'aC45M5Q4D07Pq',
       slug: 'cat-funny-animation-aC45M5Q4D07Pq',
       url: 'https://giphy.com/gifs/cat-funny-animation-aC45M5Q4D07Pq',
       bitly_gif_url: 'https://gph.is/11sgz9i',
       bitly_url: 'https://gph.is/11sgz9i',
       embed_url: 'https://giphy.com/embed/aC45M5Q4D07Pq',
       username: '',
       source: 'https://gifbinge.tumblr.com/post/56881793567/que-gustito',
       rating: 'g',
       content_url: '',
       source_tld: 'gifbinge.tumblr.com',
       source_post_url: 'https://gifbinge.tumblr.com/post/56881793567/que-gustito',
       is_sticker: 0,
       import_datetime: '2013-07-30 12:10:58',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'cat massaging GIF',
       _score: 2300047 },
     { type: 'gif',
       id: 'gl8ymnpv4Sqha',
       slug: 'cats-gl8ymnpv4Sqha',
       url: 'https://giphy.com/gifs/cats-gl8ymnpv4Sqha',
       bitly_gif_url: 'https://gph.is/1ZexrL0',
       bitly_url: 'https://gph.is/1ZexrL0',
       embed_url: 'https://giphy.com/embed/gl8ymnpv4Sqha',
       username: '',
       source: 'https://www.reddit.com/r/gifs/comments/40bwcc/cats_cuddling/',
       rating: 'g',
       content_url: '',
       source_tld: 'www.reddit.com',
       source_post_url: 'https://www.reddit.com/r/gifs/comments/40bwcc/cats_cuddling/',
       is_sticker: 0,
       import_datetime: '2016-01-10 16:25:16',
       trending_datetime: '2018-03-09 00:54:21',
       images: [Object],
       title: 'cats hugging GIF',
       _score: 2100054.8 },
     { type: 'gif',
       id: '5oBRpcOT04dq0',
       slug: 'request-cats-5oBRpcOT04dq0',
       url: 'https://giphy.com/gifs/request-cats-5oBRpcOT04dq0',
       bitly_gif_url: 'https://gph.is/1u0mLiL',
       bitly_url: 'https://gph.is/1u0mLiL',
       embed_url: 'https://giphy.com/embed/5oBRpcOT04dq0',
       username: '',
       source: 'https://www.reddit.com/r/ImageStabilization/comments/2701c6/this_cats_head_request/',
       rating: 'g',
       content_url: '',
       source_tld: 'www.reddit.com',
       source_post_url: 'https://www.reddit.com/r/ImageStabilization/comments/2701c6/this_cats_head_request/',
       is_sticker: 0,
       import_datetime: '2014-12-05 19:51:39',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'cats flailing GIF',
       _score: 2100047.8 },
     { type: 'gif',
       id: '12ipPASHq1luj6',
       slug: 'kitty-cats-funny-12ipPASHq1luj6',
       url: 'https://giphy.com/gifs/kitty-cats-funny-12ipPASHq1luj6',
       bitly_gif_url: 'https://gph.is/1xp8o9k',
       bitly_url: 'https://gph.is/1xp8o9k',
       embed_url: 'https://giphy.com/embed/12ipPASHq1luj6',
       username: '',
       source: 'https://kuronekochu.tumblr.com/post/79673402774/meow',
       rating: 'g',
       content_url: '',
       source_tld: 'kuronekochu.tumblr.com',
       source_post_url: 'https://kuronekochu.tumblr.com/post/79673402774/meow',
       is_sticker: 0,
       import_datetime: '2014-03-15 18:16:30',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'cats fail GIF',
       _score: 2100040.5 },
     { type: 'gif',
       id: 'Maz1hoeGskARW',
       slug: 'makes-highqualitygifs-Maz1hoeGskARW',
       url: 'https://giphy.com/gifs/makes-highqualitygifs-Maz1hoeGskARW',
       bitly_gif_url: 'https://gph.is/PfT3JV',
       bitly_url: 'https://gph.is/PfT3JV',
       embed_url: 'https://giphy.com/embed/Maz1hoeGskARW',
       username: '',
       source: 'https://www.reddit.com/r/HighQualityGifs/comments/20fhh3/makes_me_want_one/',
       rating: 'g',
       content_url: '',
       source_tld: 'www.reddit.com',
       source_post_url: 'https://www.reddit.com/r/HighQualityGifs/comments/20fhh3/makes_me_want_one/',
       is_sticker: 0,
       import_datetime: '2014-04-02 05:13:36',
       trending_datetime: '2014-04-02 18:05:06',
       images: [Object],
       title: 'cats kittens GIF',
       _score: 2100039.8 },
     { type: 'gif',
       id: '3o72EX5QZ9N9d51dqo',
       slug: 'producthunt-cats-music-streaming-3o72EX5QZ9N9d51dqo',
       url: 'https://giphy.com/gifs/producthunt-cats-music-streaming-3o72EX5QZ9N9d51dqo',
       bitly_gif_url: 'https://gph.is/29jEXUA',
       bitly_url: 'https://gph.is/29jEXUA',
       embed_url: 'https://giphy.com/embed/3o72EX5QZ9N9d51dqo',
       username: 'producthunt',
       source: 'https://www.producthunt.com/topics/music-streaming',
       rating: 'g',
       content_url: '',
       source_tld: 'www.producthunt.com',
       source_post_url: 'https://www.producthunt.com/topics/music-streaming',
       is_sticker: 0,
       import_datetime: '2016-06-30 23:58:11',
       trending_datetime: '2018-06-21 21:15:01',
       user: [Object],
       images: [Object],
       title: 'cats dj GIF by Product Hunt',
       _score: 2000037.6 },
     { type: 'gif',
       id: 'uB95dmqTMDCsU',
       slug: 'cat-uB95dmqTMDCsU',
       url: 'https://giphy.com/gifs/cat-uB95dmqTMDCsU',
       bitly_gif_url: 'https://gph.is/1SXGtOz',
       bitly_url: 'https://gph.is/1SXGtOz',
       embed_url: 'https://giphy.com/embed/uB95dmqTMDCsU',
       username: '',
       source: 'https://www.reddit.com/r/gifs/comments/3g3qvl/a_cat_like_this/',
       rating: 'g',
       content_url: '',
       source_tld: 'www.reddit.com',
       source_post_url: 'https://www.reddit.com/r/gifs/comments/3g3qvl/a_cat_like_this/',
       is_sticker: 0,
       import_datetime: '2015-08-07 07:02:27',
       trending_datetime: '0000-00-00 00:00:00',
       images: [Object],
       title: 'cat GIF',
       _score: 2000019.4 },
     { type: 'gif',
       id: '3oEduUVL7wX5a1NBXq',
       slug: 'afvpets-cats-pets-afv-3oEduUVL7wX5a1NBXq',
       url: 'https://giphy.com/gifs/afvpets-cats-pets-afv-3oEduUVL7wX5a1NBXq',
       bitly_gif_url: 'https://gph.is/1WJIqjD',
       bitly_url: 'https://gph.is/1WJIqjD',
       embed_url: 'https://giphy.com/embed/3oEduUVL7wX5a1NBXq',
       username: 'afvpets',
       source: '',
       rating: 'g',
       content_url: '',
       source_tld: '',
       source_post_url: '',
       is_sticker: 0,
       import_datetime: '2015-11-09 23:56:55',
       trending_datetime: '2018-02-02 20:15:01',
       user: [Object],
       images: [Object],
       title: 'hungry cats GIF by AFV Pets',
       _score: 2000016.1 },
     { type: 'gif',
       id: 'XiHEasFKRmrmw',
       slug: 'cats-hugs-shoulder-XiHEasFKRmrmw',
       url: 'https://giphy.com/gifs/cats-hugs-shoulder-XiHEasFKRmrmw',
       bitly_gif_url: 'https://gph.is/1U6PMtz',
       bitly_url: 'https://gph.is/1U6PMtz',
       embed_url: 'https://giphy.com/embed/XiHEasFKRmrmw',
       username: '',
       source: 'https://www.reddit.com/r/cats/comments/3bpib3/he_likes_to_give_hugs_but_he_cant_decide_which/',
       rating: 'g',
       content_url: '',
       source_tld: 'www.reddit.com',
       source_post_url: 'https://www.reddit.com/r/cats/comments/3bpib3/he_likes_to_give_hugs_but_he_cant_decide_which/',
       is_sticker: 0,
       import_datetime: '2015-07-01 07:30:36',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'cats hugs GIF',
       _score: 2000012.8 },
     { type: 'gif',
       id: '3o85xGRWMlHdGB1vMs',
       slug: 'afv-funny-lol-cats-3o85xGRWMlHdGB1vMs',
       url: 'https://giphy.com/gifs/afv-funny-lol-cats-3o85xGRWMlHdGB1vMs',
       bitly_gif_url: 'https://gph.is/1GweG2u',
       bitly_url: 'https://gph.is/1GweG2u',
       embed_url: 'https://giphy.com/embed/3o85xGRWMlHdGB1vMs',
       username: 'afv',
       source: '',
       rating: 'g',
       content_url: '',
       source_tld: '',
       source_post_url: '',
       is_sticker: 0,
       import_datetime: '2015-10-28 00:40:09',
       trending_datetime: '2018-06-25 07:30:01',
       user: [Object],
       images: [Object],
       title: 'fight lol GIF by America\'s Funniest Home Videos',
       _score: 1870155.2 },
     { type: 'gif',
       id: 'JfLdIahamXQI0',
       slug: 'cat-fail-JfLdIahamXQI0',
       url: 'https://giphy.com/gifs/cat-fail-JfLdIahamXQI0',
       bitly_gif_url: 'https://gph.is/XJP2Q9',
       bitly_url: 'https://gph.is/XJP2Q9',
       embed_url: 'https://giphy.com/embed/JfLdIahamXQI0',
       username: '',
       source: 'https://ihkdotgif.tumblr.com/post/41099866405',
       rating: 'g',
       content_url: '',
       source_tld: 'ihkdotgif.tumblr.com',
       source_post_url: 'https://ihkdotgif.tumblr.com/post/41099866405',
       is_sticker: 0,
       import_datetime: '2013-03-22 21:02:32',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'cat fail falling GIF',
       _score: 1311145 },
     { type: 'gif',
       id: 'aEXP6scfSSwQo',
       slug: 'aEXP6scfSSwQo',
       url: 'https://giphy.com/gifs/aEXP6scfSSwQo',
       bitly_gif_url: 'https://gph.is/299HKBX',
       bitly_url: 'https://gph.is/299HKBX',
       embed_url: 'https://giphy.com/embed/aEXP6scfSSwQo',
       username: '',
       source: 'https://imgur.com/gallery/4eJVw0b',
       rating: 'g',
       content_url: '',
       source_tld: 'imgur.com',
       source_post_url: 'https://imgur.com/gallery/4eJVw0b',
       is_sticker: 0,
       import_datetime: '2016-07-02 10:55:23',
       trending_datetime: '2017-02-17 02:30:06',
       images: [Object],
       title: 'best friends cats GIF',
       _score: 1311143.5 },
     { type: 'gif',
       id: 'W3QKEujo8vztC',
       slug: 'cats-blanket-W3QKEujo8vztC',
       url: 'https://giphy.com/gifs/cats-blanket-W3QKEujo8vztC',
       bitly_gif_url: 'https://gph.is/1Pst7YA',
       bitly_url: 'https://gph.is/1Pst7YA',
       embed_url: 'https://giphy.com/embed/W3QKEujo8vztC',
       username: '',
       source: 'https://www.reddit.com/r/gifs/comments/3v1amj/two_little_cats_under_blanket/',
       rating: 'g',
       content_url: '',
       source_tld: 'www.reddit.com',
       source_post_url: 'https://www.reddit.com/r/gifs/comments/3v1amj/two_little_cats_under_blanket/',
       is_sticker: 0,
       import_datetime: '2015-12-01 19:25:51',
       trending_datetime: '2017-11-26 21:15:02',
       images: [Object],
       title: 'cold cat GIF',
       _score: 1311141.4 },
     { type: 'gif',
       id: 'W7dBXzbnEpOBG',
       slug: 'day-cake-W7dBXzbnEpOBG',
       url: 'https://giphy.com/gifs/day-cake-W7dBXzbnEpOBG',
       bitly_gif_url: 'https://gph.is/17BBJDW',
       bitly_url: 'https://gph.is/17BBJDW',
       embed_url: 'https://giphy.com/embed/W7dBXzbnEpOBG',
       username: '',
       source: 'https://www.gifbay.com/gif/preparing_for_my_cake_day-19743/',
       rating: 'g',
       content_url: '',
       source_tld: 'www.gifbay.com',
       source_post_url: 'https://www.gifbay.com/gif/preparing_for_my_cake_day-19743/',
       is_sticker: 0,
       import_datetime: '2013-09-15 20:27:32',
       trending_datetime: '2015-09-08 18:10:40',
       images: [Object],
       title: 'shirtless arnold schwarzenegger GIF',
       _score: 1311132.8 },
     { type: 'gif',
       id: '9JLQKmspQAMWQ',
       slug: 'cat-sweet-eyes-9JLQKmspQAMWQ',
       url: 'https://giphy.com/gifs/cat-sweet-eyes-9JLQKmspQAMWQ',
       bitly_gif_url: 'https://gph.is/19o0zHa',
       bitly_url: 'https://gph.is/19o0zHa',
       embed_url: 'https://giphy.com/embed/9JLQKmspQAMWQ',
       username: '',
       source: 'https://away-on-you.tumblr.com/post/60404094493',
       rating: 'g',
       content_url: '',
       source_tld: 'away-on-you.tumblr.com',
       source_post_url: 'https://away-on-you.tumblr.com/post/60404094493',
       is_sticker: 0,
       import_datetime: '2013-09-06 01:25:21',
       trending_datetime: '2016-07-06 16:45:02',
       images: [Object],
       title: 'cat please GIF',
       _score: 1311132.5 },
     { type: 'gif',
       id: 'oMV9WErqn3ZG8',
       slug: 'na-gon-then-oMV9WErqn3ZG8',
       url: 'https://giphy.com/gifs/na-gon-then-oMV9WErqn3ZG8',
       bitly_gif_url: 'https://gph.is/141nEmb',
       bitly_url: 'https://gph.is/141nEmb',
       embed_url: 'https://giphy.com/embed/oMV9WErqn3ZG8',
       username: '',
       source: 'https://cheezburger.com/8370322944',
       rating: 'g',
       content_url: '',
       source_tld: 'cheezburger.com',
       source_post_url: 'https://cheezburger.com/8370322944',
       is_sticker: 0,
       import_datetime: '2014-11-09 21:10:37',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'feel better get well GIF',
       _score: 1311131.5 },
     { type: 'gif',
       id: 'wysyxWt4ZlQ9q',
       slug: 'bubbles-trailer-park-boys-mike-smith-wysyxWt4ZlQ9q',
       url: 'https://giphy.com/gifs/bubbles-trailer-park-boys-mike-smith-wysyxWt4ZlQ9q',
       bitly_gif_url: 'https://gph.is/1aYRvOT',
       bitly_url: 'https://gph.is/1aYRvOT',
       embed_url: 'https://giphy.com/embed/wysyxWt4ZlQ9q',
       username: '',
       source: 'https://peteneems.tumblr.com/post/112733829515',
       rating: 'g',
       content_url: '',
       source_tld: 'peteneems.tumblr.com',
       source_post_url: 'https://peteneems.tumblr.com/post/112733829515',
       is_sticker: 0,
       import_datetime: '2015-03-04 23:35:19',
       trending_datetime: '2016-01-18 19:45:01',
       images: [Object],
       title: 'trailer park boys cats GIF',
       _score: 1311131 },
     { type: 'gif',
       id: 'B6odR0DhsStfW',
       slug: 'cat-cats-B6odR0DhsStfW',
       url: 'https://giphy.com/gifs/cat-cats-B6odR0DhsStfW',
       bitly_gif_url: 'https://gph.is/1m91RAq',
       bitly_url: 'https://gph.is/1m91RAq',
       embed_url: 'https://giphy.com/embed/B6odR0DhsStfW',
       username: '',
       source: 'https://catleecious.tumblr.com/post/83146157980',
       rating: 'g',
       content_url: '',
       source_tld: 'catleecious.tumblr.com',
       source_post_url: 'https://catleecious.tumblr.com/post/83146157980',
       is_sticker: 0,
       import_datetime: '2014-04-18 23:49:04',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'cats watching GIF',
       _score: 1311129.5 },
     { type: 'gif',
       id: 'xT77XZrTKOxycjaYvK',
       slug: 'cheezburger-cats-glasses-nerds-xT77XZrTKOxycjaYvK',
       url: 'https://giphy.com/gifs/cheezburger-cats-glasses-nerds-xT77XZrTKOxycjaYvK',
       bitly_gif_url: 'https://gph.is/1TQ54S1',
       bitly_url: 'https://gph.is/1TQ54S1',
       embed_url: 'https://giphy.com/embed/xT77XZrTKOxycjaYvK',
       username: 'sheepfilms',
       source: 'https://sheepfilms.co.uk/2016/01/12/cat-glasses/',
       rating: 'g',
       content_url: '',
       source_tld: 'sheepfilms.co.uk',
       source_post_url: 'https://sheepfilms.co.uk/2016/01/12/cat-glasses/',
       is_sticker: 0,
       import_datetime: '2016-01-11 19:13:52',
       trending_datetime: '2016-01-14 23:15:01',
       user: [Object],
       images: [Object],
       title: 'cat GIF by sheepfilms',
       _score: 1311129.2 },
     { type: 'gif',
       id: 'ngs9Nqu0pqkec',
       slug: 'me-astounding-xcats-ngs9Nqu0pqkec',
       url: 'https://giphy.com/gifs/me-astounding-xcats-ngs9Nqu0pqkec',
       bitly_gif_url: 'https://gph.is/1pVOlSD',
       bitly_url: 'https://gph.is/1pVOlSD',
       embed_url: 'https://giphy.com/embed/ngs9Nqu0pqkec',
       username: '',
       source: 'https://io9.com/come-to-me-my-x-cats-professor-x-cat-video-is-astound-1600491687',
       rating: 'g',
       content_url: '',
       source_tld: 'io9.com',
       source_post_url: 'https://io9.com/come-to-me-my-x-cats-professor-x-cat-video-is-astound-1600491687',
       is_sticker: 0,
       import_datetime: '2014-07-08 02:13:08',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'cats falling off GIF',
       _score: 1311128.1 },
     { type: 'gif',
       id: '1ViLp0GBYhTcA',
       slug: 'pics-dump-eyesanity-1ViLp0GBYhTcA',
       url: 'https://giphy.com/gifs/pics-dump-eyesanity-1ViLp0GBYhTcA',
       bitly_gif_url: 'https://gph.is/ODwI8O',
       bitly_url: 'https://gph.is/ODwI8O',
       embed_url: 'https://giphy.com/embed/1ViLp0GBYhTcA',
       username: '',
       source: 'https://www.eyesanity.com/2014/03/20/the-gif-dump-50-pics-15/',
       rating: 'g',
       content_url: '',
       source_tld: 'www.eyesanity.com',
       source_post_url: 'https://www.eyesanity.com/2014/03/20/the-gif-dump-50-pics-15/',
       is_sticker: 0,
       import_datetime: '2014-03-20 06:08:25',
       trending_datetime: '2014-03-20 14:58:53',
       images: [Object],
       title: 'lil bub cat GIF',
       _score: 1311127.9 },
     { type: 'gif',
       id: 'JQRKxN6GuhGhy',
       slug: 'cats-JQRKxN6GuhGhy',
       url: 'https://giphy.com/gifs/cats-JQRKxN6GuhGhy',
       bitly_gif_url: 'https://gph.is/QCzJab',
       bitly_url: 'https://gph.is/QCzJab',
       embed_url: 'https://giphy.com/embed/JQRKxN6GuhGhy',
       username: '',
       source: 'https://www.gifbay.com/gif/cats_react_to_sound-131910/',
       rating: 'g',
       content_url: '',
       source_tld: 'www.gifbay.com',
       source_post_url: 'https://www.gifbay.com/gif/cats_react_to_sound-131910/',
       is_sticker: 0,
       import_datetime: '2014-05-13 02:34:42',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'cat GIF',
       _score: 1311127.8 },
     { type: 'gif',
       id: 'Rt3xpiV6KfibC',
       slug: 'lol-fight-come-at-me-bro-Rt3xpiV6KfibC',
       url: 'https://giphy.com/gifs/lol-fight-come-at-me-bro-Rt3xpiV6KfibC',
       bitly_gif_url: 'https://gph.is/1nCWzcX',
       bitly_url: 'https://gph.is/1nCWzcX',
       embed_url: 'https://giphy.com/embed/Rt3xpiV6KfibC',
       username: '',
       source: 'https://tumblr.4gifs.com/post/86650411704/small-cat-fights-big-cat',
       rating: 'g',
       content_url: '',
       source_tld: 'tumblr.4gifs.com',
       source_post_url: 'https://tumblr.4gifs.com/post/86650411704/small-cat-fights-big-cat',
       is_sticker: 0,
       import_datetime: '2014-05-24 02:08:14',
       trending_datetime: '1970-01-01 00:00:00',
       images: [Object],
       title: 'cats fighting GIF',
       _score: 1311127.4 } ]

      console.log(data);
      res.status(200).render(path.join(__dirname, 'index'), { data });
}));


app.listen(3000, () => console.log('Example app listening on port 3000!'))
